# Pandas 
```
pip install pandas 
pip install --upgrade pandas
```
- Pandas Series
- Pandas DataFrame --> use various ways to initialize it(dtype,columns,index)
- shape
- head
- tail
- convert to numpy array --> values
- columns
- to_csv (index = false)
- read_csv
-  drop(columns=[])
-  describe()
-  info()
-  iloc
-  loc
-  Access Particular Columns
-  indexing and slicing --> multirow and col
-  Fancy indexing
-  Filtering
-  unique
-  sort_values(by,ascending)
-  getdummies 
- groupby --> column name, various functions on grp, iterate
- pivot --> summarize and aggregate data,Grouper
- concat--> give as list, ignore_index,join
- merge--> on,how
- dropna
- fillna
- interpolate
- pip install matplotlib

In [1]:
import pandas as pd
import numpy as np

In [4]:
print(pd.__version__)

2.2.3


In [5]:
l1 = [10,20,30,40,50]

In [18]:
pds = pd.Series(l1,index = ['A','B','C','D','E'],dtype = 'f8')

In [19]:
pds

A    10.0
B    20.0
C    30.0
D    40.0
E    50.0
dtype: float64

In [20]:
pds['A']

10.0

In [8]:
type(pds)

pandas.core.series.Series

In [27]:
pds['B']

20.0

In [34]:
marks = {
    'DBMS':[25,27,0,22,23],
    'OS': [26,28,11,23,19],
    'CN': [13,25,26,30,24]
}

In [35]:
marks

{'DBMS': [25, 27, 0, 22, 23],
 'OS': [26, 28, 11, 23, 19],
 'CN': [13, 25, 26, 30, 24]}

In [40]:
df = pd.DataFrame(marks,index=['A','B','C','D','E'],columns=['DBMS','CN','OS'])

In [41]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [55]:
na = np.random.randint(50,100,(10,3))
na

array([[62, 73, 52],
       [73, 98, 50],
       [85, 78, 91],
       [77, 54, 92],
       [70, 93, 90],
       [85, 57, 77],
       [88, 78, 86],
       [60, 59, 97],
       [67, 56, 88],
       [52, 59, 96]])

In [58]:
df2 = pd.DataFrame(na,columns=['DBMS','OS','CN'])

In [59]:
df2

DBMS  OS  CN
0    62  73  52
1    73  98  50
2    85  78  91
3    77  54  92
4    70  93  90
5    85  57  77
6    88  78  86
7    60  59  97
8    67  56  88
9    52  59  96

In [60]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [61]:
df.shape

(5, 3)

In [65]:
df2.head(5)

DBMS  OS  CN
0    62  73  52
1    73  98  50
2    85  78  91
3    77  54  92
4    70  93  90

In [66]:
df2.tail(3)

DBMS  OS  CN
7    60  59  97
8    67  56  88
9    52  59  96

In [69]:
df.values

array([[25, 13, 26],
       [27, 25, 28],
       [ 0, 26, 11],
       [22, 30, 23],
       [23, 24, 19]], dtype=int64)

In [70]:
df.columns

Index(['DBMS', 'CN', 'OS'], dtype='object')

In [71]:
df2.columns

Index(['DBMS', 'OS', 'CN'], dtype='object')

In [73]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [82]:
df.to_csv("Marks.csv",sep='|')

In [78]:
ndf = pd.read_csv("Marks.csv",sep='|',index_col='Unnamed: 0')

In [79]:
ndf

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [84]:
df.to_csv("Marks.csv",sep='|',index = False)

In [85]:
ndf = pd.read_csv("Marks.csv",sep='|')
ndf

DBMS  CN  OS
0    25  13  26
1    27  25  28
2     0  26  11
3    22  30  23
4    23  24  19

In [86]:
ndf.index = ['A','B','C','D','E']

In [87]:
ndf

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [88]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [90]:
df2.describe()

DBMS         OS         CN
count  10.00000  10.000000  10.000000
mean   71.90000  70.500000  81.900000
std    11.98564  16.022554  17.214012
min    52.00000  54.000000  50.000000
25%    63.25000  57.500000  79.250000
50%    71.50000  66.000000  89.000000
75%    83.00000  78.000000  91.750000
max    88.00000  98.000000  97.000000

In [91]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DBMS    10 non-null     int32
 1   OS      10 non-null     int32
 2   CN      10 non-null     int32
dtypes: int32(3)
memory usage: 252.0 bytes


In [97]:
# df.drop(columns=['DBMS','OS'])
df.drop(index=['A','C'])

DBMS  CN  OS
B    27  25  28
D    22  30  23
E    23  24  19

In [149]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [111]:
df.iloc[::2,[0,2]]

DBMS  OS
A    25  26
C     0  11
E    23  19

In [99]:
df['DBMS']

A    25
B    27
C     0
D    22
E    23
Name: DBMS, dtype: int64

In [100]:
df[['OS','CN']]

OS  CN
A  26  13
B  28  25
C  11  26
D  23  30
E  19  24

In [106]:
df.iloc[[3,1,4,2]]

DBMS  CN  OS
D    22  30  23
B    27  25  28
E    23  24  19
C     0  26  11

In [114]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [117]:
df.loc['A':'E':2]

DBMS  CN  OS
A    25  13  26
C     0  26  11
E    23  24  19

In [131]:
df[(df['DBMS'] > 20) & (df['CN'] > 20)]

DBMS  CN  OS
B    27  25  28
D    22  30  23
E    23  24  19

In [119]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [120]:
df.iloc[[True,False,False,True,True]]

DBMS  CN  OS
A    25  13  26
D    22  30  23
E    23  24  19

In [126]:
df[df['DBMS'] >= 20]

DBMS  CN  OS
A    25  13  26
B    27  25  28
D    22  30  23
E    23  24  19

In [134]:
ndf = df[df['DBMS'] >= 20]
ndf = ndf[ndf['CN'] >= 20]
ndf

DBMS  CN  OS
B    27  25  28
D    22  30  23
E    23  24  19

In [135]:
df2

DBMS  OS  CN
0    62  73  52
1    73  98  50
2    85  78  91
3    77  54  92
4    70  93  90
5    85  57  77
6    88  78  86
7    60  59  97
8    67  56  88
9    52  59  96

In [136]:
df2['DBMS'].unique()

array([62, 73, 85, 77, 70, 88, 60, 67, 52])

In [139]:
df2['DBMS'].value_counts()

DBMS
85    2
62    1
73    1
77    1
70    1
88    1
60    1
67    1
52    1
Name: count, dtype: int64

In [140]:
a = np.array([1,3,1,2,4,1,3,2,4,1,2,3,1,4])

In [142]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4]), array([5, 3, 3, 3], dtype=int64))

In [143]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [145]:
df.sort_values(by ='DBMS',ascending=False)

DBMS  CN  OS
B    27  25  28
A    25  13  26
E    23  24  19
D    22  30  23
C     0  26  11

In [146]:
df

DBMS  CN  OS
A    25  13  26
B    27  25  28
C     0  26  11
D    22  30  23
E    23  24  19

In [148]:
df.sort_values(by = 'A',axis = 1)

CN  DBMS  OS
A  13    25  26
B  25    27  28
C  26     0  11
D  30    22  23
E  24    23  19

In [150]:
pds = pd.Series(['A','B','C','B','A','B'])

In [151]:
pds

0    A
1    B
2    C
3    B
4    A
5    B
dtype: object

In [152]:
pdd = pd.get_dummies(pds,dtype='i1')

In [153]:
pdd

A  B  C
0  1  0  0
1  0  1  0
2  0  0  1
3  0  1  0
4  1  0  0
5  0  1  0

In [154]:
data = pd.read_csv("weather_data_cities.csv")

In [158]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [161]:
data[data['city'] == 'new york']['temperature'].mean()

32.25

In [163]:
data[data['city'] == 'mumbai']['temperature'].mean()

88.5

In [164]:
gdf = data.groupby(by = 'city')

In [165]:
for city,group in gdf:
    print(city)
    print(group)
    print()

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy



In [166]:
gdf['temperature'].mean()

city
mumbai      88.50
new york    32.25
paris       47.75
Name: temperature, dtype: float64

In [168]:
gdf = data.groupby(by = 'event')
gdf['windspeed'].mean()

event
Cloudy    10.333333
Fog       13.500000
Rain       5.500000
Snow      12.000000
Sunny      9.750000
Name: windspeed, dtype: float64

In [169]:
data

day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [171]:
data.pivot(columns='day',index='city')

temperature                            windspeed                    \
day         1/1/2017 1/2/2017 1/3/2017 1/4/2017  1/1/2017 1/2/2017 1/3/2017   
city                                                                          
mumbai            90       85       87       92         5       12       15   
new york          32       36       28       33         6        7       12   
paris             45       50       54       42        20       13        8   

                     event                             
day      1/4/2017 1/1/2017 1/2/2017 1/3/2017 1/4/2017  
city                                                   
mumbai          5    Sunny      Fog      Fog     Rain  
new york        7     Rain    Sunny     Snow    Sunny  
paris          10    Sunny   Cloudy   Cloudy   Cloudy

In [172]:
d1 = {
    'A' : [10,20,30,40],
    'B' : [3,4,5,6]
}
d2 = {
    'A' : [30,40,50,60],
    'C' : [3,4,5,6]
}

In [173]:
df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [174]:
df1

A  B
0  10  3
1  20  4
2  30  5
3  40  6

In [175]:
df2

A  C
0  30  3
1  40  4
2  50  5
3  60  6

In [182]:
df3 = pd.concat([df1,df2],join = 'outer')
df3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  NaN
3  40  6.0  NaN
0  30  NaN  3.0
1  40  NaN  4.0
2  50  NaN  5.0
3  60  NaN  6.0

In [189]:
mdf3 = pd.merge(df1,df2,how='outer')
mdf3

A    B    C
0  10  3.0  NaN
1  20  4.0  NaN
2  30  5.0  3.0
3  40  6.0  4.0
4  50  NaN  5.0
5  60  NaN  6.0

In [190]:
mdf3.dropna()

A    B    C
2  30  5.0  3.0
3  40  6.0  4.0

In [192]:
mdf3.fillna(mdf3.mean())

A    B    C
0  10  3.0  4.5
1  20  4.0  4.5
2  30  5.0  3.0
3  40  6.0  4.0
4  50  4.5  5.0
5  60  4.5  6.0

In [198]:
mdf3.mean()

A    35.0
B     4.5
C     4.5
dtype: float64

In [209]:
mdf3.interpolate('linear',limit_direction='both')

A    B    C
0  10  3.0  3.0
1  20  4.0  3.0
2  30  5.0  3.0
3  40  6.0  4.0
4  50  6.0  5.0
5  60  6.0  6.0